name: Renovate

on:
  pull_request:
    branches:
      - main

jobs:
  renovate-config-check:
    name: 'renovate:config'
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/release'
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        check-latest: true

    - name: Install Renovate
      run: npm install -g renovate

    - name: Check Renovate configuraton
      run: renovate-config-validator
